### PR TITLE
Document built-in feature in PHPUnit to randomize tests

### LINKED ISSUE #30: You don't need this - There is a default PHPUnit feature --order-by=random
For everybody that finds this repo and wants to try it out: you don't need this. 

You can run the following:
```
vendor/bin/phpunit --order-by=random
```

To the author: It would be great if you could change the readme of this project to say it's not needed anymore, because PHPUnit has an `--order-by=random` feature.

Best,

Ruud

### PR DESCRIPTION
**Pull request by fiunchinho**
Fixes #30 , #29

### CODE REVIEW

**Comment by fiunchinho** [comment]
Please @ruudk take a look

**Review by ruudk — COMMENTED** [review]
Might be nice to include my snippet to make it easier to reproduce a failed build with a seed

**Comment by fiunchinho** [comment]
I believe it would be better to link to the official docs, but since there are none, I'll add your snippet and remove it with a link to the official docs when available.

**Comment by fiunchinho** [comment]
Done

**Review by ruudk — APPROVED** [review]
Great

**Comment by fiunchinho** [comment]
Thanks!

**Pull request merged**
